<template>
  <PageLayout title="Glossary of Terms" prev-link="" home-link="" next-link="">
    <template #content>
      <p><strong>Beta:</strong> A measure of a stock's volatility in relation to the overall market.</p>

      <p><strong>Book Value:</strong> The net asset value of a company, calculated by subtracting total liabilities from
        total assets.</p>

      <p><strong>Capital Expenditure (CapEx):</strong> Funds used by a company to acquire, upgrade, or maintain physical
        assets such as property, buildings, or equipment.</p>

      <p><strong>Debt-to-Equity Ratio:</strong> A ratio that indicates the relative proportion of a company's debt to
        its shareholders' equity.</p>

      <p><strong>Dividend Yield:</strong> The dividend per share, divided by the price per share, representing the
        return on investment for a stock based on its dividend payments.</p>

      <p><strong>Dividends:</strong> A portion of a company's earnings that is paid out to shareholders, usually in cash
        or additional stock.</p>

      <p><strong>EBITDA Margin:</strong> Shows a company's operating profit as a percentage of its revenue, often used
        to compare profitability between companies.</p>

      <p><strong>Earnings Before Interest and Taxes (EBIT):</strong> A measure of a company's profitability that
        excludes interest and income tax expenses.</p>

      <p><strong>Earnings Growth Rate:</strong> The rate at which a company’s earnings are increasing or decreasing over
        a period.</p>

      <p><strong>Earnings Per Share (EPS):</strong> A portion of a company's profit allocated to each outstanding share
        of common stock.</p>

      <p><strong>Free Cash Flow (FCF):</strong> The cash a company generates after accounting for cash outflows to
        support operations and maintain its capital assets.</p>

      <p><strong>Institutional Investors:</strong> Large organizations like banks and hedge funds that invest large sums
        of money into financial markets.</p>

      <p><strong>Liquidity:</strong> The ability of a company to quickly convert assets into cash without losing value.
      </p>

      <p><strong>Market Capitalization (Market Cap):</strong> The total market value of a company’s outstanding shares
        of stock. It represents the market's view of a company’s total worth.</p>

      <p><strong>Net Income:</strong> The total profit a company has after subtracting all of its expenses.</p>

      <p><strong>Operating Cash Flow (OCF):</strong> The cash generated by a company’s regular business operations.</p>

      <p><strong>Operating Margin:</strong> A profitability ratio that shows what percentage of a company’s revenue is
        left after paying for variable costs of production.</p>

      <p><strong>Price-to-Book (P/B) Ratio:</strong> A financial ratio that compares a company's market value to its
        book value.</p>

      <p><strong>Price-to-Earnings (P/E) Ratio:</strong> A financial metric that compares a company’s share price to its
        earnings per share (EPS).</p>

      <p><strong>Price-to-Sales (P/S) Ratio:</strong> A financial metric that compares a company's stock price to its
        revenues.</p>

      <p><strong>Return on Equity (ROE):</strong> A measure of financial performance, showing how efficiently a company
        is using its equity to generate profits.</p>

      <p><strong>Revenue:</strong> The total income generated by a company from its sales of goods or services before
        any expenses are deducted.</p>

      <p><strong>Revenue Growth:</strong> The increase in a company's sales over a specific period.</p>

      <p><strong>Short Interest:</strong> The total number of shares that have been sold short but have not yet been
        covered or closed out.</p>

      <p><strong>Stock Buyback (Share Repurchase):</strong> When a company buys back its own shares from the
        marketplace, reducing the number of outstanding shares.</p>

      <p><strong>Trailing Price/Earnings to Growth (PEG) Ratio:</strong> A stock’s price-to-earnings (P/E) ratio divided
        by the growth rate of its earnings.</p>

      <p><strong>Volatility:</strong> A statistical measure of the dispersion of returns for a given security or market
        index.</p>

      <p><strong>Yield Curve:</strong> A graph that plots the interest rates of bonds having equal credit quality but
        different maturity dates.</p>

    </template>
  </PageLayout>
</template>

<script setup lang="ts">
import PageLayout from '@/components/PageLayout.vue';

useHead({
  title: 'Glossary of Stock Market Terms - Investing Definitions',
  meta: [
    {
      name: 'description',
      content: 'Explore a comprehensive glossary of stock market and investing terms, including financial ratios, metrics, and concepts used in stock analysis.'
    },
    {
      name: 'keywords',
      content: 'stock market glossary, investing terms, financial metrics, P/E ratio, ROE, stock analysis, market capitalization, EBITDA, dividends'
    }
  ]
});
</script>
